/**
 * Database types - Generated by Supabase CLI
 * Run: pnpm supabase gen types typescript --local > src/types/database.ts
 *
 * This is a placeholder file. Replace with generated types after Supabase setup.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>; // Will be populated by Supabase CLI
    Views: Record<string, never>; // Will be populated by Supabase CLI
    Functions: Record<string, never>; // Will be populated by Supabase CLI
    Enums: Record<string, never>; // Will be populated by Supabase CLI
  };
}
