/**
 * Core type definitions for the AI Ad Agency system
 */

// Agent types
export type AgentType =
  | 'market-intelligence'
  | 'performance-testing'
  | 'creative'
  | 'campaign-execution'
  | 'orchestrator';

export type AgentStatus = 'idle' | 'running' | 'paused' | 'error' | 'completed';

// Platform types
export type AdPlatform = 'meta' | 'tiktok';

// Campaign types
export type CampaignObjective =
  | 'OUTCOME_AWARENESS'
  | 'OUTCOME_ENGAGEMENT'
  | 'OUTCOME_LEADS'
  | 'OUTCOME_SALES'
  | 'OUTCOME_TRAFFIC';

export type CampaignStatus = 'ACTIVE' | 'PAUSED' | 'ARCHIVED' | 'DELETED';

// Creative types
export type CreativeFormat = 'image' | 'video' | 'carousel';

export type ApprovalStatus = 'pending' | 'approved' | 'rejected' | 'revision_requested';

// Re-export database types (will be generated by Supabase)
export type { Database } from './database';
